# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
 - package-ecosystem: "maven"
    directory: "/config-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/gateway"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/discovery"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/run-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/user-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/statistics-service"
    schedule:
      interval: "weekly"
