spring:
  cloud:
    gateway:
      routes:
        - id: run-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/runs/**
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/users/**
        - id: statistics-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/statistics/**
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always