server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: run-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/runs/**
        - id: run-service-swagger
          uri: http://localhost:8060
          predicates:
            - Path=/swagger-ui.html
            - Path=/swagger-ui/index.html
            - Path=/v3/api-docs/**
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/users/**
        - id: statistics-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/statistics/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always