server:
  port: 8060
spring:
  application:
    name: run-service
  datasource:
    url: jdbc:postgresql://localhost:5433/runs
    username: myuser
    password: passwordToChange
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        data-locations: classpath:loadData.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
runs.upload:
  kafka:
    topic: run.upload

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

user:
  service:
    url: http://localhost:8090/api/v1/users
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
#        include: "*"
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
springdoc:
  api-docs:
    path: /run-service/v3/api-docs
  swagger-ui:
    path: /run-service/swagger-ui.html
  packagesToScan: com.runner.runs
  cache:
    disabled: true
logging:
  level:
    com.runner.runs: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  file:
    name: ./run-service/logs/run-service.log