server:
  port: 8050
spring:
  application:
    name: statistics-service

  datasource:
    url: jdbc:postgresql://localhost:5431/rankings
    username: myuser
    password: passwordToChange
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: runEvents
runs.upload:
  kafka:
    topic: run.upload
notifications:
  kafka:
    topic: midnight.ranking.notification
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /statistics-service/v3/api-docs
  swagger-ui:
    path: /statistics-service/swagger-ui.html

logging:
  level:
    com.runner.statistics: DEBUG