server:
    port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
#        git:
#          uri: https://github.com/pouliose/microservices-config
#          clone-on-start: true