eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
    port: 8761
    eviction-interval-timer-in-ms: 60000
    renewal-threshold-update-interval-ms: 60000
spring:
    config:
        import: optional:configserver:http://localhost:8888