eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8060
spring:
  application:
    name: run-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5433/runs
    username: myuser
    password: passwordToChange
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        data-locations: classpath:loadData.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: runEvents

runs:
  kafka:
    topic: run.upload
logging:
  level:
    com.runner.runs: DEBUG
  file:
    name: ./run-service/logs/run-service.log