name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build commons project
      run: |
        cd commons
        mvn clean package
        mvn install -Dfile='target\commons-1.0.1.jar' -DgroupId='com.runner' -DartifactId='commons' -Dversion='1.0.1' -Dpackaging='jar'
        
    - name: Build config-service with Maven
      run: mvn -B package --file config-service/pom.xml
    - name: Build gateway with Maven
      run: mvn -B package --file gateway/pom.xml
    - name: Build discovery with Maven
      run: mvn -B package --file discovery/pom.xml
    - name: Build run-service with Maven
      run: mvn -B package --file run-service/pom.xml
    - name: Build user-service with Maven
      run: mvn -B package --file user-service/pom.xml
    - name: Build statistics-service with Maven
      run: mvn -B package --file statistics-service/pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph for commons
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: commons
        
    - name: Update dependency graph for config-service
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: config-service

    - name: Update dependency graph for gateway
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: gateway

    - name: Update dependency graph for discovery
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: discovery

    - name: Update dependency graph for run-service
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: run-service

    - name: Update dependency graph for user-service
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: user-service

    - name: Update dependency graph for statistics-service
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: statistics-service
